### ISSUE TITLE
Backend Compiling issue

### ISSUE THREAD

**Issue by Sury1a** [eevan7a9/real-estate-management#14]
Hi ..I have sucessfully compiled and runned the frontend code it is working,but the backend code is nat compiling and showing some errors .I dont know what to do so please tell me how to run the code
<img width="560" alt="Screenshot_20230218_102917" src="https://user-images.githubusercontent.com/77194503/219838960-f150a91b-7e7c-450a-8637-cf59f929e2ec.png">

**Comment by eevan7a9** [comment]
Hello, sorry late reply, 
are you in `/backend-fastify`  root folder?, and have done `npm install` then `npm run dev`?

**Comment by Sury1a** [comment]
Thank you that problem is resolved i am facing new problem 
<img width="935" alt="Screenshot_20230221_101831" src="https://user-images.githubusercontent.com/77194503/220250401-ab646553-85ca-4e75-b078-9ceec772b7a6.png">
Mongo db errors and too much of errors
please tell me how to run the backend code

**Comment by eevan7a9** [comment]
it looks like a database connection problem, are you sure you added your DB_CONNECT correctly?
can you share your .env file?

**Comment by Sury1a** [comment]
yeah sure
<img width="319" alt="Screenshot_20230221_194746" src="https://user-images.githubusercontent.com/77194503/220369950-189d3887-89e1-4d5e-9c27-b94b023c0dc4.png">

**Comment by Sury1a** [comment]
Please tell me how to setup mongodb and connect to the code after that how should i run the whole code?

**Comment by eevan7a9** [comment]
what is your mongodb version? are you sure it was installed correctly?
can you copy & paste the error message?

**Comment by Sury1a** [comment]
Hi bro I solved the error thanks for your responses
