### ISSUE TITLE
Backend - Add User Change Password Functionality to Backend

### ISSUE THREAD

**Issue by eevan7a9** [eevan7a9/real-estate-management#21]
### Add chage password functionality 

We need to implement a feature that allows users to change their passwords securely through the backend API.

- Create a new endpoint in the backend API specifically for handling password updates.
- Ensure that the endpoint follows secure practices such as password hashing and validation.
- Implement necessary validation checks to verify the authenticity of the user requesting the password change.

**Comment by mucoban** [comment]
hi @eevan7a9, I would like to implement this issue. Can you assing it to me please

**Comment by eevan7a9** [comment]
Hello @mucoban ,

Thank you for your interest in contributing.

I can assigned the ticket to you. Feel free to make a PR.
I can update the ticket description to make it easier to understand if needed.
and feel free to ask questions.

Btw, have you managed to run the app on your local machine?

**Comment by mucoban** [comment]
yes, @eevan7a9 , I managed to run the app on my local. Description is clear, thank you. I am starting to implementation. I will create a pr after completing.
<img width="1728" alt="image" src="https://github.com/eevan7a9/real-estate-management/assets/80916997/c0bb3240-82c9-4406-960a-cbdc2b35a3a1">

**Comment by eevan7a9** [comment]
@mucoban Thank you for confirming. Take your time. If you have any questions or need assistance along the way, don't hesitate to reach out.

**Comment by eevan7a9** [comment]
Thank you for your contribution! 🔥🔥🔥
