### ISSUE TITLE
Frontend - confirm password not being checked on changing password

### ISSUE THREAD

**Issue by mucoban** [eevan7a9/real-estate-management#38]
On `/user/account/change-password` page, it is not being checked whether Password New and Password Confirm are same when a user want to change their password.

**Expectation**
When Password New and Password Confirm are not same, an error should be shown and it should be disabled to submit the form.

**Comment by mucoban** [comment]
Can you assign the issue to me @eevan7a9

**Comment by eevan7a9** [comment]
@mucoban  yeah sure

**Comment by mucoban** [comment]
hi @eevan7a9 , I created a pr, can you review
