### ISSUE TITLE
Frontend - Enquiries list rework, add filters on query params and add additional filters "Sent" & "Received"

### ISSUE THREAD

**Issue by eevan7a9** [eevan7a9/real-estate-management#40]
Rework the enquiries list on the frontend to include filters based on query parameters and add additional filters for "Sent" and "Received" enquiries.

- Rework the existing enquiries list to support filtering based on query parameters.
- Ensure that the enquiries list dynamically updates based on the applied filters.
- Introduce two new filters: "Sent" and "Received".

Currently, when people filter/sort, the query URL still remains 
`localhost:8100/enquiries`.

What we want is to update the url query params.
For example, if we filter by sales and sort by title:
`localhost:8100/enquiries?filter=sales&sort=title`

this can be helpful for:
Bookmarking / Debugging

**Comment by mucoban** [comment]
hi @eevan7a9, can you assign the ticket to me please?

**Comment by eevan7a9** [comment]
yea sure, you can take it if you want
