### ISSUE TITLE
database connection issue 

### ISSUE THREAD

**Issue by chiragbiradar** [eevan7a9/real-estate-management#9]
Hey, I am unable to connect database properly. Can you provide detailed information on how to connect nodejs and mongodb.
while adding properties I am getting error :
"Error:Http failure response for http://localhost:8000/properties: 0 Unknown Error"
and after this the backend has stopped

**Comment by eevan7a9** [comment]
after installing the dependencies have you created a ".env" file in the root directory of the "backend-fastify/"?

then add credentials to it?

example:
.env
```
PORT=8000
LOGGER=true
SALT=12
SECRET_KEY='secret'
DB_CONNECT=mongodb://localhost:27017/rem-db2
```

**Comment by chiragbiradar** [comment]
> after installing the dependencies have you created a ".env" file in the root directory of the "backend-fastify/"?
> 
> then add credentials to it?
> 
> example: .env
> 
> ```
> PORT=8000
> LOGGER=true
> SALT=12
> SECRET_KEY='secret'
> DB_CONNECT=mongodb://localhost:27017/rem-db2
> ```

Yes I have created .env file
![image](https://user-images.githubusercontent.com/78417411/205010195-89da1363-5138-4d9a-8c3e-e173230b795d.png)


Its showing this:
![image](https://user-images.githubusercontent.com/78417411/205009977-a8e78699-e0e8-46a0-bde5-b4969cea03af.png)

**Comment by eevan7a9** [comment]
@chiragbiradar  What version of mongodb are you using in you local machine?

can you try this on "index.js" on mongoose.connect update the parameter.

```
  .connect(process.env.DB_CONNECT, {
    useUnifiedTopology: true,
    useNewUrlParser: true,
    family: 4, <--- add this
  }) 

  .then(() => {
    ...
```


you can also try the answers on stackoverflow:
[MongooseServerSelectionError: connect ECONNREFUSED ::1:27017](https://stackoverflow.com/questions/69840504/mongooseserverselectionerror-connect-econnrefused-127017)

**Comment by chiragbiradar** [comment]
@eevan7a9 I am using version 6.0.2
![image](https://user-images.githubusercontent.com/78417411/205426425-a9c4e9b6-e333-481e-aa0d-5e72afa6dab3.png)

I added family: 4 but its still not working

**Comment by eevan7a9** [comment]
Is your mongodb up and running smoothly?
type `mongo` in terminal
[ref](https://stackoverflow.com/questions/39944481/how-to-check-if-mongodb-server-is-running-in-pc)


if you want you can try my .env

PORT=8000
LOGGER=true
SALT=12
SECRET_KEY='secret'
DB_CONNECT=mongodb+srv://admin-test:eOfRLjDS6y2BJXqB@rem.1in0012.mongodb.net/?retryWrites=true&w=majority

**Comment by eevan7a9** [comment]
@chiragbiradar   can you pull the latest changes, I allowed 'uploads/' folder
seems like adding properties is looking for 'uploads/' folder. if it's missing will cause error

**Comment by chiragbiradar** [comment]
@eevan7a9 
Yes I pulled the new change Its still not working, its showing
![image](https://user-images.githubusercontent.com/78417411/205498416-1f504684-54a1-408d-8b40-72f27f98704a.png)

should I change mongodb version?
or I think there is some problem in angular routing. Can you go through it and let me know?

**Comment by chiragbiradar** [comment]
Yes its working now 
@eevan7a9 
Thank you for helping

**Comment by eevan7a9** [comment]
@chiragbiradar  No worries, I still don't know why you received those undefined errors.

Nonetheless, it's good to know that it's working.
